apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  annotations:
    lldap: https://github.com/nitnelave/lldap
    k8s: https://github.com/Evantage-WS/lldap-kubernetes
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ldap
      port: {{ .Values.service.ports.ldap }}
      targetPort: ldap
    {{- if include "lldap.sslEnabled" . }}
    - name: ldaps
      port: {{ .Values.service.ports.ldaps }}
      targetPort: ldaps
    {{- end }}
    - name: web
      port: {{ .Values.service.ports.web }}
      targetPort: web
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
